### ISSUE TITLE
Uncaught SoundValidationError

### ISSUE THREAD

**Issue by alyssaruth** [mdr/web-sampler#635]
I was trying to capture some audio via tab sharing in chrome@windows with [this video](https://www.youtube.com/watch?v=uelA7KRLINA), but kept getting:

```
index-i3PiRLMM.js:90 Uncaught SoundValidationError: Sound ebfeaab3-1f60-4649-a8fe-6a225e7e41a0 sample is out of range: -1.0005680322647095
    at Hhe (index-i3PiRLMM.js:90:23921)
    at Vhe (index-i3PiRLMM.js:90:23595)
    at Uhe (index-i3PiRLMM.js:90:23257)
    at Array.forEach (<anonymous>)
    at zhe.validate (index-i3PiRLMM.js:90:22831)
    at eI (index-i3PiRLMM.js:90:22721)
    at Yhe.setState (index-i3PiRLMM.js:90:31020)
    at Yhe.setSounds (index-i3PiRLMM.js:90:30850)
    at Yhe.updateSoundPure (index-i3PiRLMM.js:90:30806)
    at Yhe.updateSound (index-i3PiRLMM.js:90:30494)
    at Yhe.setAudioData (index-i3PiRLMM.js:90:27518)
    at index-i3PiRLMM.js:212:5211
    at index-i3PiRLMM.js:88:13098
    at Array.forEach (<anonymous>)
    at qfe.fireRecordingCompleteListeners (index-i3PiRLMM.js:88:13087)
    at qfe.stopRecording (index-i3PiRLMM.js:88:14937)
    at MediaStream.<anonymous> (index-i3PiRLMM.js:88:13555)
    at MediaStream.r (index-i3PiRLMM.js:32:2522)
```

After a few attempts/refreshes it "succeeded", but the result was a distorted clip that was much too long for the snippet I'd recorded:

[broken sound.zip](https://github.com/user-attachments/files/17722904/broken.sound.zip)

From then on, the same length issue was happening for any clip I tried to capture. 🤔

**Comment by mdr** [comment]
Thanks for the bug report! I was able to reproduce the sample out of range problem. While it seems that [samples should be in the range [-1, 1]](https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletProcessor/process#inputs), it seems that Chrome sometimes can produce samples outside that range. Should now be fixed!

The distorted/incorrect length captured clip could potentially be a different issue; I wasn't able to reproduce it.
